name: Build Unsigned Applications

on:
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§¹ â€¢ Clean Environment
        run: |
          rm -rf node_modules
          rm -rf android
          rm -rf ios
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf $HOME/.gradle/caches/
       
  build_ios:
    needs: clean
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: ğŸ“€ â€¢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: ğŸ—‚ï¸ â€¢ Install Node Dependencies
        run: npm install --legacy-peer-deps

      - name: ğŸ”¨ â€¢ Prebuild iOS
        run: |
          npx expo prebuild -p ios

      - name: ğŸ—ï¸ â€¢ Build iOS
        run: |
          cd ios
          xcodebuild -workspace Papillon.xcworkspace \
                     -scheme Papillon \
                     -configuration Release \
                     -destination generic/platform=iOS \
                     -derivedDataPath ./build \
                     IPHONEOS_DEPLOYMENT_TARGET=15.1 \
                     CODE_SIGN_STYLE=Manual \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGN_IDENTITY="iPhone Distribution" \
     
      - name: ğŸ“¦ â€¢ Bundle IPA
        run: |
          cd ios
          mkdir -p build
          mkdir -p Payload
          cp -r build/Build/Products/Release-iphoneos/Papillon.app Payload/
          zip -r Papillon.ipa Payload
          mv Papillon.ipa build/Papillon.ipa
          rm -rf Payload

      - name: ğŸŒ â€¢ Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: ios/build/Papillon.ipa
          if-no-files-found: error

  build_android:
    needs: clean
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
     
      - name: ğŸ“€ â€¢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: â˜• â€¢ Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '20'

      - name: ğŸ—‚ï¸ â€¢ Install Node Dependencies
        run: npm install --legacy-peer-deps

      - name: ğŸ”¨ â€¢ Prebuild Android
        run: |
          npx expo prebuild -p android

      - name: ğŸ—ï¸ â€¢ Build Android
        run: |
          cd android
          ./gradlew assembleRelease

      - name: ğŸŒ â€¢ Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/release/app-release.apk